# Generated by Django 2.2.3 on 2019-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisteapi', '0002_auto_20190717_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='musicGenre',
            field=models.IntegerField(choices=[(1, 'hipop'), (2, 'pop')], max_length=1),
        ),
    ]
