# Generated by Django 2.2.3 on 2019-07-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisteapi', '0003_auto_20190724_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
