# Generated by Django 2.2.3 on 2019-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisteapi', '0004_auto_20190726_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='musicGenre',
            field=models.IntegerField(choices=[(1, 'hipop'), (2, 'afro'), (3, 'indie'), (4, 'k-pop'), (5, 'pop')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='originFlag',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
