# Generated by Django 2.2.3 on 2019-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisteapi', '0005_auto_20190729_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiste',
            name='avatarImage',
            field=models.ImageField(default='media/defaults/no-img.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='firstName',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='lastName',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='origin',
            field=models.CharField(default='noorigin', max_length=120),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='originFlag',
            field=models.ImageField(default='media/defaults/no-img.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='worldRank',
            field=models.IntegerField(default='1000000000'),
        ),
    ]
