# Generated by Django 2.2.3 on 2019-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisteapi', '0006_auto_20190729_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='avatarImage',
            field=models.ImageField(default='media/defaults/avartar-default.png', upload_to='media/'),
        ),
    ]
