# Generated by Django 2.2.3 on 2019-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
