# Generated by Django 2.2.3 on 2019-07-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0002_auto_20190724_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media'),
        ),
    ]
