# Generated by Django 2.2.3 on 2019-07-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0004_auto_20190729_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='media/no-img.jpg', upload_to='media/'),
        ),
    ]
