# Generated by Django 2.2.3 on 2019-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0005_auto_20190729_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='isExplicit',
            field=models.BooleanField(default=False),
        ),
    ]
