# Generated by Django 2.2.3 on 2019-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0006_music_isexplicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='musicGenre',
            field=models.IntegerField(choices=[(1, 'hipop'), (2, 'afro'), (3, 'indie'), (4, 'k-pop'), (5, 'pop')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='media/defaults/no-img.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='musicFile',
            field=models.FileField(default='media/defaults/Krazy-Rymz-My-Matter_1lzbZGR.mp3', upload_to='media/'),
        ),
    ]
